// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfhwjxmkuzkusteehugq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmaHdqeG1rdXprdXN0ZWVodWdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0Mjk3MDEsImV4cCI6MjA2NDAwNTcwMX0.N7TF3RbVnuf7udozoazuFocylRs6IweRHvEudfFUgSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});